### PR TITLE
Implement basic rest api architecture

### PR DESCRIPTION
**Pull request by sterchelen**
* Use https://github.com/gorilla/mux for http routing
* Introduce https://github.com/sirupsen/logrus for logging
ref https://github.com/peopledoc/peopleinfra/issues/8328

### CODE REVIEW

**Comment by sterchelen** [comment]
It is a work in progress.

Too basic to be used. We should add a better structure. That smells bad code for having a lot of code for just a small api. Need to think about it.

**Comment by SwannCroiset** [comment]
nice,

missing validation some where when the "env" is not found (expected 404)
```
curl http://0.0.0.0:8080/hosts/foo/fo
curl: (52) Empty reply from server
```
panic:

```
./bin/jarvis  --debug server 
TRAC[0002] hosts path called                            
2020/08/24 14:47:38 http: panic serving 127.0.0.1:39156: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc0001154a0)
	net/http/server.go:1767 +0x139
panic(0x916900, 0xdad340)
	runtime/panic.go:679 +0x1b2
jarvis/internal/pkg/environment.GetFullPathInventoriesFromEnvironments(0xc000028240, 0x33, 0xc0001074e0, 0x1, 0x1, 0x6, 0x6, 0xc000121380, 0xc000144000, 0x45)
	jarvis@/internal/pkg/environment/finder.go:75 +0xe7
jarvis/api/handlers.inventoriesReaders(0xc0001074e0, 0x1, 0x1, 0x3, 0x0, 0xa5bb60, 0xc00015f4c0, 0x203000)
	jarvis@/api/handlers/hosts.go:83 +0x7c
jarvis/api/handlers.hostsHandler.list(0xc000111420, 0xa65540, 0xc0001001c0, 0xc0000d8e00)
	jarvis@/api/handlers/hosts.go:30 +0x241
net/http.HandlerFunc.ServeHTTP(0xc00006dc60, 0xa65540, 0xc0001001c0, 0xc0000d8e00)
	net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000122000, 0xa65540, 0xc0001001c0, 0xc0000d8c00)
	github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001000e0, 0xa65540, 0xc0001001c0, 0xc0000d8c00)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001154a0, 0xa669c0, 0xc000034a80)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2928 +0x384
```

**Comment by sterchelen** [comment]
Panic fixed @SwannCroiset :)

**Review by SwannCroiset — APPROVED** [review]

**Comment by sterchelen** [comment]
Waiting @damienbertau to validate the correct responses :)

**Review by damienbertau — APPROVED** [review]
Everything is ok for me. Thanks for your work @sterchelen !

**Comment by sterchelen** [comment]
I will rebase this work to have a clear git history and then make a new release

**Pull request merged**
